### PR TITLE
[ELY-1713] Restore Javadoc Generation

### PR DESCRIPTION
**Pull request by skyllarr**
All javadoc will be generated at one place to /wildfly-elytron/target/site/apidocs/full-javadoc/

Additional dependency for javadoc plugin is needed because of this: 
https://stackoverflow.com/a/28755606

### CODE REVIEW

**Comment by darranl** [comment]
@Skyllarr At the moment does this just to the full-javadoc?  We will also need the api-javadoc as before so we can continue to publish the same pair.

**Comment by fjuma** [comment]
@Skyllarr The list of ```sourceFileIncludes``` will also need to be checked to make sure any new public packages also get included in ```api-javadoc```. (You can refer to our [Module Review Spreadsheet](https://docs.google.com/spreadsheets/d/11B6rRnW18gL5zTBuyC-qxb8rMfpF7GfVWxrWFZqRiaQ/edit?usp=sharing) to check which ones are public.)

**Comment by skyllarr** [comment]
@darranl Should the api-javadoc be generated for each module separately to the module's folder, or at one place in the parent module?

**Comment by Skyllarr** [comment]
@darranl Should the api-javadoc be generated for each module separately to the module's folder, or at one place in the parent module?

**Comment by darranl** [comment]
For now I think we want complete generation so the end result looks the same.

We will at some point also want to generate per module javadoc but I think visit that as a separate step as we still need to clean up modules that contain public and private API as that is not a good practice anyway.

**Comment by darranl** [comment]
@Skyllarr Using OpenJDK 11 I am currently getting this error: -

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 45.102 s
[INFO] Finished at: 2019-01-14T14:38:24+00:00
[INFO] Final Memory: 125M/454M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0-M1:aggregate (api-javadoc) on project wildfly-elytron-parent: An error has occurred in Javadoc report generation:
[ERROR] Exit code: 1 - /home/darranl/src/refactoring/wildfly-elytron/wildfly-elytron-auth-server/src/main/java/org/wildfly/security/authz/MappedRoleMapper.java:42: warning - Tag @link: reference not found: #initialize(Map<String, String>)
[ERROR] /home/darranl/src/refactoring/wildfly-elytron/wildfly-elytron-x500-cert/src/main/java/org/wildfly/security/x500/cert/InhibitAnyPolicyExtension.java:36: warning - invalid usage of tag >
[ERROR] /home/darranl/src/refactoring/wildfly-elytron/wildfly-elytron-x500-cert/src/main/java/org/wildfly/security/x500/cert/NameConstraintsExtension.java:89: warning - invalid usage of tag >
[ERROR] /home/darranl/src/refactoring/wildfly-elytron/wildfly-elytron-x500-cert/src/main/java/org/wildfly/security/x500/cert/NameConstraintsExtension.java:90: warning - invalid usage of tag >
[ERROR] /home/darranl/src/refactoring/wildfly-elytron/wildfly-elytron-x500-cert/src/main/java/org/wildfly/security/x500/cert/PKCS10CertificateSigningRequest.java:68: warning - invalid usage of tag &id
[ERROR] /home/darranl/src/refactoring/wildfly-elytron/wildfly-elytron-x500-cert/src/main/java/org/wildfly/security/x500/cert/PKCS10CertificateSigningRequest.java:69: warning - invalid usage of tag &Type
[ERROR] /home/darranl/src/refactoring/wildfly-elytron/wildfly-elytron-x500-cert/src/main/java/org/wildfly/security/x500/cert/PKCS10CertificateSigningRequest.java:73: warning - invalid usage of tag &id
[ERROR] /home/darranl/src/refactoring/wildfly-elytron/wildfly-elytron-x500-cert/src/main/java/org/wildfly/security/x500/cert/PKCS10CertificateSigningRequest.java:74: warning - invalid usage of tag &Type
[ERROR] /home/darranl/src/refactoring/wildfly-elytron/wildfly-elytron-security-manager/src/main/java/org/wildfly/security/manager/JDKSpecific.java:20: error: cannot find symbol
[ERROR] import sun.reflect.Reflection;
[ERROR] ^
[ERROR] symbol:   class Reflection
[ERROR] location: package sun.reflect
[ERROR] 
[ERROR] Command line was: /home/darranl/applications/java/openjdk-11.0.1/bin/javadoc @options @argfile

**Comment by fjuma** [comment]
@Skyllarr I think restoring the changes from this PR should fix this:

https://github.com/wildfly-security/wildfly-elytron/pull/1205

**Comment by skyllarr** [comment]
I am having difficulties with error JDKSpecific.java:20: error: cannot find symbol
import sun.reflect.Reflection;
Before it was fixed with this in the pom:

```
<sourceFileExcludes>
      <exclude>org/wildfly/security/manager/JDKSpecific.java</exclude>
 </sourceFileExcludes>
```
Maven-javadoc-plugin uses javadoc tool underneath. If this plugin is run with -X option (e.g mvn javadoc:javadoc -X ) it will generate 3 files: argfile (files that will be passed to javadoc tool), options (for javadoc tool) and javadoc.sh, which is script that only executes ( /usr/lib/jvm/java-11-openjdk-11.0.1.13-1.fc29.x86_64/bin/javadoc @ options @argfile ) .
In unsplitted Elytron, the above sourceFileExcludes did single difference to these files: it removed wildfly-elytron/src/main/java/org/wildfly/security/manager/JDKSpecific.java row from argfile. If file is excluded the javadoc is generated fine, otherwise it fails with error above. 

For the splitted version, this exclusion works the same (when used it will remove JDKSpecific.java from argfile). However, the error will appear anyway.

**Pull request closed without merging**
