### PR TITLE
[ELY-1711] Create new `wildfly-elytron-sasl-digest` module

### PR DESCRIPTION
**Pull request by fjuma**
For the SASL mechanisms, I think it makes more sense to split out the logging messages after new modules have been created for all of the mechanisms. Each SASL mechanism implementation uses both messages that are common to all SASL mechanisms as well as mechanism-specific messages. Currently, `org.wildfly.security.sasl.util.AbstractSaslParticipant` takes `org.wildfly.security._private.ElytronMessages` as a parameter. Once new modules have been created for all of the mechanisms, we'll likely want to add an `ElytronMessages` class for the common SASL messages, then add new mechanism-specific `ElytronMessages` classes that extend the common one, and add a new `AbstractSaslParticipant` constructor to take the common one as a parameter.

### CODE REVIEW

**Comment by dmlloyd** [comment]
A bit late I guess, but DigestUtil doesn't have to be in _private anymore.  It can move into the main package and be package-private.

**Comment by darranl** [comment]
@dmlloyd Just added your comment to the TODO list on the etherpad.

**Comment by dmlloyd** [comment]
I can do a PR for it if you want, I just didn't want to step on Farah & Justin's toes.

**Comment by darranl** [comment]
Maybe just wait until I have HTTP Digest in as well, with these Digest utils we may want something common.

**Comment by dmlloyd** [comment]
Maybe.  It would be good to extract a mechanisms/digest at some point for shared code.

**Pull request merged**
